# Generated by Django 4.0.2 on 2022-02-20 10:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Recieved Contacts',
            },
        ),
        migrations.CreateModel(
            name='UnitTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_code', models.CharField(blank=True, help_text='Generated automaticall', max_length=15, null=True, unique=True)),
                ('full_name', models.CharField(max_length=20)),
                ('visitor_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15)),
                ('visit_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today, message='Past dates are not allowed!')])),
                ('message', models.TextField(blank=True, null=True)),
                ('visit_status', models.CharField(choices=[('cancelled', 'Cancelled'), ('waiting', 'Waiting'), ('visited', 'Visited')], default='waiting', max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental_property.rentalunit')),
            ],
        ),
    ]
