# Generated by Django 4.0.2 on 2022-02-20 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenants_rented_unit'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittour',
            options={'verbose_name_plural': 'Scheduled Visits'},
        ),
        migrations.CreateModel(
            name='VacateNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_out_notice', models.DateField()),
                ('reason', models.TextField(max_length=255)),
                ('notice_status', models.CharField(choices=[('dropped', 'Dropped'), ('Approved', 'Approved'), ('checking', 'Checking')], max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
            ],
        ),
    ]
