# Generated by Django 4.0.2 on 2022-02-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenants_rented_unit'),
        ('core', '0002_alter_unittour_options_vacatenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittour',
            name='last_updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.managers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unittour',
            name='visit_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('waiting', 'Waiting'), ('approved', 'Approved'), ('visited', 'Visited')], default='waiting', max_length=10),
        ),
    ]
