# Generated by Django 4.0.2 on 2022-02-21 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenants_rented_unit'),
        ('rental_property', '0002_alter_rentalunit_maintanance_status'),
        ('core', '0003_unittour_last_updated_by_alter_unittour_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvictionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('notice_detail', models.TextField(max_length=1000)),
                ('help_contact_phone', models.CharField(max_length=14)),
                ('help_contact_email', models.EmailField(max_length=50)),
                ('evition_status', models.CharField(choices=[('initiated', 'Initiated'), ('inprogress', 'In Progress'), ('evicted', 'Evicted'), ('dropped', 'Dropped')], default='initiated', max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.managers')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental_property.rentalunit')),
            ],
        ),
    ]
