# Generated by Django 4.0.2 on 2022-02-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evictionnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evictionnotice',
            name='evition_status',
        ),
        migrations.AddField(
            model_name='evictionnotice',
            name='eviction_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('evicted', 'Evicted'), ('dropped', 'Dropped')], default='initiated', max_length=10),
        ),
    ]
