# Generated by Django 4.0.2 on 2022-02-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenants_rented_unit'),
        ('core', '0006_alter_evictionnotice_sent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionnotice',
            name='sent_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.managers'),
            preserve_default=False,
        ),
    ]
