# Generated by Django 4.0.2 on 2022-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_move_out_notice_vacatenotice_move_out_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacatenotice',
            options={'verbose_name': "Tenant's Notices To Move Out", 'verbose_name_plural': "Tenant's Notices To Move Out"},
        ),
        migrations.AddField(
            model_name='vacatenotice',
            name='drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacatenotice',
            name='notice_status',
            field=models.CharField(choices=[('received', 'Recieved'), ('dropped', 'Dropped'), ('Approved', 'Approved'), ('checking', 'Checking')], default='received', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacatenotice',
            name='reason',
            field=models.TextField(max_length=2000),
        ),
    ]
