# Generated by Django 4.0.2 on 2022-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vacatenotice_options_vacatenotice_drop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacatenotice',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
