# Generated by Django 4.0.2 on 2022-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vacatenotice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacatenotice',
            name='drop',
            field=models.BooleanField(default=False, verbose_name='I would like to drop this notice'),
        ),
        migrations.AlterField(
            model_name='vacatenotice',
            name='notice_status',
            field=models.CharField(choices=[('received', 'Recieved'), ('dropped', 'Dropped'), ('confirmed', 'Confirmed'), ('checking', 'Checking')], default='received', max_length=10),
        ),
    ]
