# Generated by Django 4.0.2 on 2022-03-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('core', '0011_alter_vacatenotice_drop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittour',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.managers'),
        ),
    ]
