# Generated by Django 4.0.2 on 2022-03-06 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_unittour_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='evictionnotice',
            name='eviction_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
