# Generated by Django 4.0.2 on 2022-03-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('core', '0013_evictionnotice_eviction_due'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacateNotice',
            new_name='MoveOutNotice',
        ),
    ]
