# Generated by Django 4.0.2 on 2022-03-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('core', '0015_servicerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerating',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants'),
            preserve_default=False,
        ),
    ]
