# Generated by Django 4.0.2 on 2022-03-08 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_servicerating_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerating',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
