# Generated by Django 4.0.2 on 2022-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_servicerating_created_servicerating_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerating',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
