# Generated by Django 4.0.2 on 2022-03-09 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_servicerating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerating',
            name='drag',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
