# Generated by Django 4.0.2 on 2022-03-09 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_servicerating_drag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerating',
            name='drag',
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
