# Generated by Django 4.0.2 on 2022-03-09 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_servicerating_drag_alter_servicerating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerating',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
