# Generated by Django 4.0.2 on 2022-03-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_servicerating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='evictionnotice',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
