# Generated by Django 4.0.2 on 2022-03-12 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('core', '0023_evictionnotice_send_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTenantCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.managers')),
                ('sent_to', models.ManyToManyField(related_name='tenant_coms', to='accounts.Tenants')),
            ],
        ),
    ]
