# Generated by Django 4.0.2 on 2022-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('core', '0026_alter_managertenantcommunication_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertenantcommunication',
            name='send_to_all',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='managertenantcommunication',
            name='sent_to',
            field=models.ManyToManyField(blank=True, to='accounts.Tenants'),
        ),
    ]
