# Generated by Django 4.0.2 on 2022-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('core', '0028_remove_managertenantcommunication_sent_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managertenantcommunication',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='managertenantcommunication',
            name='sent_to',
            field=models.ManyToManyField(to='accounts.Tenants'),
        ),
    ]
