# Generated by Django 4.0.2 on 2022-03-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_managertenantcommunication_sent_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertenantcommunication',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
