# Generated by Django 4.0.2 on 2022-03-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('core', '0030_alter_managertenantcommunication_send_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertenantcommunication',
            name='sent_to',
            field=models.ManyToManyField(blank=True, to='accounts.Tenants'),
        ),
    ]
