# Generated by Django 4.0.2 on 2022-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_managertenantcommunication_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertenantcommunication',
            name='ref_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
