# Generated by Django 4.0.2 on 2022-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_managertenantcommunication_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertenantcommunication',
            name='retract',
            field=models.BooleanField(default=False),
        ),
    ]
