# Generated by Django 4.0.2 on 2022-03-13 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0009_remove_maintanancenotice_unit'),
        ('accounts', '0005_alter_tenants_associated_account'),
        ('core', '0033_managertenantcommunication_retract'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.building')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.managers')),
            ],
        ),
    ]
