# Generated by Django 4.0.2 on 2022-03-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tenantemails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managertenantcommunication',
            options={'verbose_name_plural': 'Archives | Manager E-Mails'},
        ),
        migrations.AlterModelOptions(
            name='tenantemails',
            options={'verbose_name_plural': 'Archives | E-mails From Tenants'},
        ),
        migrations.RemoveField(
            model_name='evictionnotice',
            name='help_contact_email',
        ),
        migrations.RemoveField(
            model_name='evictionnotice',
            name='help_contact_phone',
        ),
    ]
