# Generated by Django 4.0.2 on 2022-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_managertenantcommunication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionnotice',
            name='notice_detail',
            field=models.TextField(),
        ),
    ]
