# Generated by Django 4.0.2 on 2022-03-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_tenants_associated_account'),
        ('core', '0036_alter_evictionnotice_notice_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveoutnotice',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moveoutnotice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants'),
        ),
    ]
