# Generated by Django 4.0.2 on 2022-03-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_moveoutnotice_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Visitor Contact'},
        ),
        migrations.AlterModelOptions(
            name='moveoutnotice',
            options={'verbose_name': "Tenant's To Move Out Notice", 'verbose_name_plural': "Tenant's To Move Out Notice"},
        ),
        migrations.AddField(
            model_name='contact',
            name='ref_code',
            field=models.CharField(default=27838872278, max_length=15),
            preserve_default=False,
        ),
    ]
