# Generated by Django 4.0.2 on 2022-03-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_contact_options_alter_moveoutnotice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ref_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
