# Generated by Django 4.0.2 on 2022-03-14 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_contact_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerating',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rate us'),
        ),
    ]
