# Generated by Django 4.0.2 on 2022-03-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_contactreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Received Contact'},
        ),
    ]
