# Generated by Django 4.0.2 on 2022-02-24 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rent_and_utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='paid_for_month',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='paid_in_advance',
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='rent_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rent_and_utility.unitrentdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitrentdetails',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=34, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitrentdetails',
            name='amount_paid_in_advance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitrentdetails',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitrentdetails',
            name='paid_in_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitrentdetails',
            name='pay_for_month',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], default=23, max_length=47),
            preserve_default=False,
        ),
    ]
