# Generated by Django 4.0.2 on 2022-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='maintanance_status',
            field=models.CharField(choices=[('nm', 'Needs Inspection'), ('ip', 'Initiating Inspection'), ('ir', 'Maintanance In Progress'), ('op', 'No Active Reports')], default='op', max_length=6),
        ),
    ]
