# Generated by Django 4.0.2 on 2022-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0002_alter_rentalunit_maintanance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='building-cover'),
        ),
    ]
