# Generated by Django 4.0.2 on 2022-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0003_building_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_status',
            field=models.CharField(choices=[('op', 'Vacancies Available'), ('um', 'Under Maintanance'), ('fo', 'Fully Occupied'), ('dc', 'Decomisioned')], max_length=5),
        ),
    ]
