# Generated by Django 4.0.2 on 2022-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0004_alter_building_building_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='maintanance_status',
            field=models.CharField(choices=[('nm', 'Unchechecked Report'), ('ip', 'Initiating Inspection'), ('ir', 'Maintanance In Progress'), ('op', 'No Active Reports'), ('rm', 'Remove')], default='op', max_length=6),
        ),
    ]
