# Generated by Django 4.0.2 on 2022-03-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0006_maintanancenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanancenotice',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintanancenotice',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Leave blank for general notice', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rental_property.rentalunit'),
        ),
    ]
