# Generated by Django 4.0.2 on 2022-03-07 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0007_maintanancenotice_send_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintanancenotice',
            old_name='to_date_time',
            new_name='from_date',
        ),
        migrations.RemoveField(
            model_name='maintanancenotice',
            name='from_date_time',
        ),
        migrations.AddField(
            model_name='maintanancenotice',
            name='to_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
