# Generated by Django 4.0.2 on 2022-03-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0008_rename_to_date_time_maintanancenotice_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintanancenotice',
            name='unit',
        ),
    ]
