# Generated by Django 4.0.2 on 2022-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0009_remove_maintanancenotice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='status',
            field=models.CharField(choices=[('occupied', 'Currently Occupied'), ('ready', 'Ready To Move In'), ('hold', 'On Hold'), ('maintanance', 'Under Maintanance')], default='ready', max_length=20),
        ),
    ]
