# Generated by Django 4.0.2 on 2022-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0011_alter_rentalunit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanancenotice',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
