# Generated by Django 4.0.2 on 2022-03-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0013_alter_maintanancenotice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintanancenotice',
            name='status',
        ),
        migrations.AddField(
            model_name='maintanancenotice',
            name='maintanance_status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
