# Generated by Django 4.0.2 on 2022-02-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenants_rented_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prefered_payment_method',
        ),
    ]
