# Generated by Django 4.0.2 on 2022-03-20 18:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='active_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='active_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+254779957530', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
