# Generated by Django 4.0.3 on 2022-03-30 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usernotifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotifications',
            options={'verbose_name': 'Notifications', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
