# Generated by Django 4.0.3 on 2022-04-02 17:24

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usernotifications_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants')),
            ],
            options={
                'verbose_name': 'Related Records',
                'verbose_name_plural': 'Related Records',
            },
        ),
        migrations.CreateModel(
            name='RelatedRecordsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.get_related_record_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.relatedrecords')),
            ],
            options={
                'verbose_name': 'Files',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
