# Generated by Django 4.0.3 on 2022-04-02 17:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_relatedrecords_relatedrecordsfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedrecords',
            name='file',
            field=models.FileField(default='inline.jpeg', upload_to=accounts.models.get_related_record_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RelatedRecordsFiles',
        ),
    ]
