# Generated by Django 4.0.2 on 2022-02-26 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_profile_prefered_payment_method'),
        ('rental_property', '0005_alter_rentalunit_maintanance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_for_month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('remarks', models.TextField(blank=True)),
                ('cleared', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('due_date', models.DateField()),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental_property.rentalunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('paybill_number', models.CharField(help_text='Not required for bank transfer', max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_for_month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('remarks', models.TextField(blank=True)),
                ('cleared', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('due_date', models.DateField()),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental_property.rentalunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilities_and_rent.water')),
            ],
        ),
        migrations.CreateModel(
            name='UnitRentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_for_month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('paid_in_advance', models.BooleanField(default=False)),
                ('amount_paid_in_advance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cleared', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('due_date', models.DateField()),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updatd', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.rentalunit')),
            ],
            options={
                'verbose_name': 'Rent For Unit',
                'verbose_name_plural': 'Rent Details',
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paid_for_month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(help_text='If rejected...Reason..')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.managers')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilities_and_rent.paymentmethods')),
                ('rent_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilities_and_rent.unitrentdetails')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilities_and_rent.electricity')),
            ],
        ),
    ]
