# Generated by Django 4.0.2 on 2022-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='paybill_number',
            field=models.CharField(blank=True, help_text='Not required for bank transfer', max_length=20, null=True),
        ),
    ]
