# Generated by Django 4.0.2 on 2022-02-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0002_alter_paymentmethods_paybill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid_in_advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
