# Generated by Django 4.0.2 on 2022-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0003_alter_unitrentdetails_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
