# Generated by Django 4.0.2 on 2022-02-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0006_alter_unitrentdetails_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid_in_advance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='rent_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
