# Generated by Django 4.0.2 on 2022-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0007_alter_unitrentdetails_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
