# Generated by Django 4.0.2 on 2022-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0008_alter_unitrentdetails_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='amount_paid_in_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
