# Generated by Django 4.0.2 on 2022-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0011_unitrentdetails_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
