# Generated by Django 4.0.2 on 2022-02-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0012_alter_unitrentdetails_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitrentdetails',
            old_name='updatd',
            new_name='updated',
        ),
    ]
