# Generated by Django 4.0.2 on 2022-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0013_rename_updatd_unitrentdetails_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitrentdetails',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
