# Generated by Django 4.0.2 on 2022-02-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0014_unitrentdetails_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
