# Generated by Django 4.0.2 on 2022-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0015_rentpayment_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitrentdetails',
            name='status',
            field=models.CharField(choices=[('payment_made', 'Payment Made'), ('no_payment', 'No Payment Made')], default='no_payment', max_length=15),
        ),
    ]
