# Generated by Django 4.0.2 on 2022-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0017_alter_rentpayment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='account_name',
            field=models.CharField(default='BnG Management', max_length=50),
            preserve_default=False,
        ),
    ]
