# Generated by Django 4.0.2 on 2022-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0018_paymentmethods_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='name',
            field=models.CharField(help_text='mpesa, bank transfer e.g. kcb', max_length=30),
        ),
    ]
