# Generated by Django 4.0.2 on 2022-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0019_alter_paymentmethods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitrentdetails',
            name='notify_tenant',
            field=models.BooleanField(default=True),
        ),
    ]
