# Generated by Django 4.0.2 on 2022-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0020_unitrentdetails_notify_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='notify_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
