# Generated by Django 4.0.2 on 2022-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0021_rentpayment_notify_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason, if rejected'),
        ),
    ]
