# Generated by Django 4.0.2 on 2022-02-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0022_rentpayment_confirm_alter_rentpayment_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentpayment',
            old_name='confirm',
            new_name='confirmed',
        ),
    ]
