# Generated by Django 4.0.2 on 2022-02-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0023_rename_confirm_rentpayment_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='pay_for_month',
            new_name='month',
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_consuption', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('added', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.water')),
            ],
        ),
    ]
