# Generated by Django 4.0.2 on 2022-02-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0024_rename_pay_for_month_water_month_waterconsumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterconsumption',
            old_name='weeks_consuption',
            new_name='weeks_consumption',
        ),
    ]
