# Generated by Django 4.0.2 on 2022-02-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0026_alter_water_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
