# Generated by Django 4.0.2 on 2022-02-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0027_alter_water_quantity_alter_water_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterconsumption',
            old_name='weeks_consumption',
            new_name='weekly_consumption',
        ),
    ]
