# Generated by Django 4.0.2 on 2022-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0028_rename_weeks_consumption_waterconsumption_weekly_consumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='unit',
            new_name='measuring_unit',
        ),
        migrations.RenameField(
            model_name='waterconsumption',
            old_name='weekly_consumption',
            new_name='consumption',
        ),
        migrations.RenameField(
            model_name='waterconsumption',
            old_name='added',
            new_name='reading_added',
        ),
        migrations.AddField(
            model_name='water',
            name='lock_cycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='water',
            name='meter_number',
            field=models.CharField(default=23, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='current_reading',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='previous_reading',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=9),
            preserve_default=False,
        ),
    ]
