# Generated by Django 4.0.2 on 2022-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0005_alter_rentalunit_maintanance_status'),
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('utilities_and_rent', '0029_rename_unit_water_measuring_unit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Water',
            new_name='WaterBilling',
        ),
        migrations.RenameField(
            model_name='waterpayments',
            old_name='utility',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='waterpayments',
            name='remarks',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
    ]
