# Generated by Django 4.0.2 on 2022-03-02 17:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0031_alter_electricity_options_alter_waterbilling_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbilling',
            name='bill_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='month',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47, null=True),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Unit Price (KES)'),
        ),
    ]
