# Generated by Django 4.0.2 on 2022-03-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0032_waterbilling_bill_code_alter_waterbilling_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbilling',
            name='bill_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
