# Generated by Django 4.0.2 on 2022-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0033_alter_waterbilling_bill_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterconsumption',
            name='reading_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
