# Generated by Django 4.0.2 on 2022-03-02 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0034_alter_waterconsumption_reading_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbilling',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
