# Generated by Django 4.0.2 on 2022-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0036_alter_waterbilling_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbilling',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
