# Generated by Django 4.0.2 on 2022-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0037_alter_waterbilling_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbilling',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waterconsumption',
            name='reading_added',
            field=models.DateField(auto_now=True),
        ),
    ]
