# Generated by Django 4.0.2 on 2022-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0039_alter_waterconsumption_reading_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterconsumption',
            name='reading_added',
            field=models.DateField(),
        ),
    ]
