# Generated by Django 4.0.2 on 2022-03-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0040_alter_waterconsumption_reading_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbilling',
            name='re_billed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
