# Generated by Django 4.0.2 on 2022-03-03 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0041_waterbilling_re_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpayments',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
