# Generated by Django 4.0.2 on 2022-03-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0042_waterpayments_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpayments',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
