# Generated by Django 4.0.2 on 2022-03-04 12:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('rental_property', '0005_alter_rentalunit_maintanance_status'),
        ('utilities_and_rent', '0043_alter_waterpayments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=20)),
                ('units', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_for_month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('remarks', models.TextField(blank=True)),
                ('cleared', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('due_date', models.DateField()),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental_property.rentalunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
            ],
            options={
                'verbose_name_plural': 'Billing | Electricity',
            },
        ),
        migrations.CreateModel(
            name='ElectricityReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('units', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reading_date', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.electricitybilling')),
            ],
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='rental_unit',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.RemoveField(
            model_name='electricitypayments',
            name='utility',
        ),
        migrations.DeleteModel(
            name='Electricity',
        ),
        migrations.AddField(
            model_name='electricitypayments',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='utilities_and_rent.electricitybilling'),
            preserve_default=False,
        ),
    ]
