# Generated by Django 4.0.2 on 2022-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0044_electricitybilling_electricityreadings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitybilling',
            name='unit',
        ),
        migrations.AddField(
            model_name='electricitybilling',
            name='bill_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='electricitybilling',
            name='lock_cycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricitybilling',
            name='measuring_unit',
            field=models.CharField(default='KWH', max_length=20),
        ),
    ]
