# Generated by Django 4.0.2 on 2022-03-04 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0045_remove_electricitybilling_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybilling',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='electricitybilling',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
