# Generated by Django 4.0.2 on 2022-03-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0046_electricitybilling_added_electricitybilling_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricitybilling',
            old_name='pay_for_month',
            new_name='month',
        ),
    ]
