# Generated by Django 4.0.2 on 2022-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0047_rename_pay_for_month_electricitybilling_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybilling',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
