# Generated by Django 4.0.2 on 2022-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0048_alter_electricitybilling_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypayments',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitypayments',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electricitypayments',
            name='payment_method',
            field=models.CharField(help_text='e.g. MPESA, KCB ...', max_length=30),
        ),
        migrations.AlterField(
            model_name='waterpayments',
            name='payment_method',
            field=models.CharField(help_text='e.g. MPESA, KCB ...', max_length=30),
        ),
    ]
