# Generated by Django 4.0.2 on 2022-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0049_electricitypayments_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitypayments',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
