# Generated by Django 4.0.2 on 2022-03-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0050_alter_electricitypayments_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitybilling',
            options={'verbose_name_plural': 'Billing | Electricity Billing Cycles'},
        ),
        migrations.AlterModelOptions(
            name='electricitypayments',
            options={'verbose_name': 'Billing | Electricity Bill Payments', 'verbose_name_plural': 'Billing | Electricity Bill Payments'},
        ),
        migrations.AlterModelOptions(
            name='waterbilling',
            options={'verbose_name_plural': 'Billing | Water Billing Cycles'},
        ),
        migrations.AlterModelOptions(
            name='waterpayments',
            options={'verbose_name': 'Billing | Water Bills Payments', 'verbose_name_plural': 'Billing | Water Bills Payments'},
        ),
    ]
