# Generated by Django 4.0.2 on 2022-03-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0051_alter_electricitybilling_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitrentdetails',
            name='amount_paid_in_advance',
        ),
        migrations.RemoveField(
            model_name='unitrentdetails',
            name='paid_in_advance',
        ),
    ]
