# Generated by Django 4.0.2 on 2022-03-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0052_remove_unitrentdetails_amount_paid_in_advance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbilling',
            old_name='quantity',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='waterbilling',
            name='measuring_unit',
        ),
    ]
