# Generated by Django 4.0.2 on 2022-03-07 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0053_rename_quantity_waterbilling_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypayments',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
