# Generated by Django 4.0.2 on 2022-03-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0055_electricitybilling_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybilling',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
