# Generated by Django 4.0.2 on 2022-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0056_alter_electricitybilling_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypayments',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
