# Generated by Django 4.0.2 on 2022-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0059_alter_waterpayments_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbilling',
            name='re_billed',
        ),
        migrations.AddField(
            model_name='waterbilling',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
