# Generated by Django 4.0.2 on 2022-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0060_remove_waterbilling_re_billed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpayments',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
