# Generated by Django 4.0.2 on 2022-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0062_unitrentdetails_rent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('open', 'open'), ('closed', 'closed'), ('unconfirmed', 'unconfirmed')], default='open', max_length=15),
        ),
    ]
