# Generated by Django 4.0.2 on 2022-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0063_alter_unitrentdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('open', 'open'), ('closed', 'closed')], default='open', max_length=15),
        ),
    ]
