# Generated by Django 4.0.2 on 2022-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0065_watermeter_electricitymeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermeter',
            name='ssid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
