# Generated by Django 4.0.2 on 2022-03-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0009_remove_maintanancenotice_unit'),
        ('utilities_and_rent', '0066_watermeter_ssid_alter_electricitymeter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitymeter',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_meters', to='rental_property.rentalunit'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_meters', to='rental_property.rentalunit'),
        ),
    ]
