# Generated by Django 4.0.2 on 2022-03-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenants_rented_unit'),
        ('rental_property', '0009_remove_maintanancenotice_unit'),
        ('utilities_and_rent', '0067_alter_electricitymeter_unit_alter_watermeter_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybilling',
            name='rental_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.rentalunit'),
        ),
        migrations.AlterField(
            model_name='electricitybilling',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants'),
        ),
        migrations.AlterField(
            model_name='electricitypayments',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.electricitybilling'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.paymentmethods'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants'),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='rental_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.rentalunit'),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants'),
        ),
        migrations.AlterField(
            model_name='waterpayments',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.waterbilling'),
        ),
    ]
