# Generated by Django 4.0.2 on 2022-03-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0069_alter_waterbilling_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybilling',
            name='meter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.electricitymeter'),
        ),
    ]
