# Generated by Django 4.0.2 on 2022-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0070_alter_electricitybilling_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybilling',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
