# Generated by Django 4.0.2 on 2022-03-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0073_alter_electricitybilling_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbilling',
            name='meter_rent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=9),
        ),
    ]
