# Generated by Django 4.0.2 on 2022-03-14 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0074_waterbilling_meter_rent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitybilling',
            options={'verbose_name_plural': 'Billing 3 | Electricity Billing Cycles'},
        ),
        migrations.AlterModelOptions(
            name='electricitypayments',
            options={'verbose_name': 'Billing 3 | Electricity Bill Payments', 'verbose_name_plural': 'Billing 3 | Electricity Bill Payments'},
        ),
        migrations.AlterModelOptions(
            name='rentpayment',
            options={'verbose_name_plural': 'Billing 1 | Rent Payments'},
        ),
        migrations.AlterModelOptions(
            name='unitrentdetails',
            options={'verbose_name': 'Rent For Unit', 'verbose_name_plural': 'Billing 1 | Rent Details'},
        ),
        migrations.AlterModelOptions(
            name='waterbilling',
            options={'verbose_name_plural': 'Billing 2 | Water Billing Cycles'},
        ),
        migrations.AlterModelOptions(
            name='waterpayments',
            options={'verbose_name': 'Billing 2 | Water Billing Payments', 'verbose_name_plural': 'Billing 2 | Water Billing Payments'},
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
