# Generated by Django 4.0.2 on 2022-03-14 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0075_alter_electricitybilling_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbilling',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
