# Generated by Django 4.0.2 on 2022-03-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0009_remove_maintanancenotice_unit'),
        ('utilities_and_rent', '0076_alter_waterbilling_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitymeter',
            name='for_building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental_property.building'),
            preserve_default=False,
        ),
    ]
