# Generated by Django 4.0.2 on 2022-03-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0077_electricitymeter_for_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitymeter',
            name='for_building',
        ),
    ]
