# Generated by Django 4.0.2 on 2022-03-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0079_alter_paymentmethods_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitypayments',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Message?'),
        ),
        migrations.AlterField(
            model_name='waterpayments',
            name='remarks',
            field=models.TextField(blank=True, max_length=155, null=True, verbose_name='Message?'),
        ),
    ]
