# Generated by Django 4.0.2 on 2022-03-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0080_alter_electricitypayments_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('open', 'open'), ('closed', 'closed'), ('defaulted', 'Defaulted')], default='open', max_length=15),
        ),
    ]
