# Generated by Django 4.0.2 on 2022-03-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0081_alter_unitrentdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
