# Generated by Django 4.0.2 on 2022-03-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0082_alter_unitrentdetails_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrentdetails',
            name='rent_type',
            field=models.CharField(choices=[('rent', 'Monthly Rent'), ('s_deposit', 'Security Deposit')], default='rent', max_length=15),
        ),
    ]
