# Generated by Django 4.0.2 on 2022-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0084_rentpayment_paid_with_stripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('bill_name', models.CharField(max_length=20)),
            ],
        ),
    ]
