# Generated by Django 4.0.2 on 2022-03-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0085_stripepay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepay',
            name='bill_name',
        ),
    ]
