# Generated by Django 4.0.2 on 2022-03-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0087_alter_rentpayment_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripePay',
        ),
    ]
