# Generated by Django 4.0.2 on 2022-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0088_delete_stripepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('description', models.TextField()),
                ('phone_number', models.TextField()),
                ('amount', models.TextField()),
                ('reference', models.TextField()),
                ('organization_balance', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
    ]
