# Generated by Django 4.0.2 on 2022-03-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0089_testmpesa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMpesa',
        ),
    ]
