# Generated by Django 4.0.2 on 2022-03-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0091_mpesapaymentsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MpesaPaymentsModel',
            new_name='MpesaPayments',
        ),
    ]
