# Generated by Django 4.0.2 on 2022-03-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0092_rename_mpesapaymentsmodel_mpesapayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayments',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
