# Generated by Django 4.0.2 on 2022-03-20 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0096_rename_mpesapayent_mpesapayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapayment',
            old_name='request_id',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='description',
            field=models.TextField(default='we'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='first_name',
            field=models.CharField(default='dsd', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='last_name',
            field=models.CharField(default='ksd', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='middle_name',
            field=models.CharField(default='nfm', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='organization_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='type',
            field=models.CharField(default='paybill', max_length=55),
            preserve_default=False,
        ),
    ]
