# Generated by Django 4.0.2 on 2022-03-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0097_rename_request_id_mpesapayment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='paid_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.unitrentdetails'),
            preserve_default=False,
        ),
    ]
