# Generated by Django 4.0.2 on 2022-03-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0098_mpesapayment_paid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='middle_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='reference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
