# Generated by Django 4.0.2 on 2022-03-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities_and_rent', '0099_alter_mpesapayment_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOnlineMpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=225)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reference', models.CharField(max_length=255)),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities_and_rent.unitrentdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
    ]
