# Generated by Django 4.0.2 on 2022-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_managers_active_phone_number_and_more'),
        ('utilities_and_rent', '0100_payonlinempesa_delete_mpesapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_manager', to='accounts.managers'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_code',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='rent_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='utilities_and_rent.unitrentdetails'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='accounts.tenants'),
        ),
    ]
