# Generated by Django 4.0.2 on 2022-03-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_hiredpersonnel_hired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredpersonnel',
            name='phone_number',
            field=models.CharField(default=238932030, max_length=15),
            preserve_default=False,
        ),
    ]
