# Generated by Django 4.0.2 on 2022-03-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_personnelcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_order_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personnelcontact',
            name='body',
            field=models.TextField(max_length=255),
        ),
    ]
