# Generated by Django 4.0.2 on 2022-03-11 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_remove_workorder_unit_workorder_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='workorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
