# Generated by Django 4.0.2 on 2022-03-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0008_workorder_created_workorder_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='est_duration',
            field=models.CharField(help_text='e.g. 2 days', max_length=70),
        ),
    ]
