# Generated by Django 4.0.2 on 2022-03-11 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_alter_complaints_status'),
        ('work_order', '0009_alter_workorder_est_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='additional_workers',
            field=models.ManyToManyField(blank=True, related_name='other_workers', to='work_order.HiredPersonnel'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='parent_report',
            field=models.ForeignKey(blank=True, help_text='Leave blank for general work order', null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.unitreport'),
        ),
    ]
