# Generated by Django 4.0.2 on 2022-03-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0011_workorder_email_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting Assignment'), ('in-progress', 'In-Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
