# Generated by Django 4.0.2 on 2022-03-12 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0012_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting Assignment'), ('assigned', 'Assigned'), ('in-progress', 'In-Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkOrderPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('payment_code', models.CharField(max_length=30)),
                ('paid_to', models.CharField(max_length=55)),
                ('payment_method', models.CharField(help_text='e.g Mpesa', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_date', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.workorder')),
            ],
        ),
    ]
