# Generated by Django 4.0.2 on 2022-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0013_alter_workorder_status_workorderpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredpersonnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
