# Generated by Django 4.0.2 on 2022-03-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0014_hiredpersonnel_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderpayments',
            old_name='paid_to',
            new_name='paid_to_name',
        ),
        migrations.AddField(
            model_name='workorderpayments',
            name='paid_to_account',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
