# Generated by Django 4.0.2 on 2022-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0015_rename_paid_to_workorderpayments_paid_to_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='email_personnel',
            field=models.BooleanField(default=True),
        ),
    ]
