# Generated by Django 4.0.2 on 2022-02-20 10:59

import complaints.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_property', '0001_initial'),
        ('accounts', '0002_tenants_rented_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=155)),
                ('status', models.CharField(choices=[('rc', 'Received'), ('rs', 'Resolved')], default='rc', max_length=5)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='UnitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rc', 'Received'), ('pr', 'Processing'), ('rs', 'Resolved')], default='rr', max_length=5)),
                ('desc', models.TextField(max_length=255, verbose_name='Describe the situation')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, help_text='Field generated automatically', max_length=30, null=True, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Report Types',
            },
        ),
        migrations.CreateModel(
            name='UnitReportAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to=complaints.models.get_report_image_path, width_field='image_width')),
                ('image_width', models.IntegerField(default=600)),
                ('image_height', models.IntegerField(default=500)),
                ('unit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.unitreport')),
            ],
        ),
        migrations.AddField(
            model_name='unitreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='complaints.unitreporttype'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental_property.rentalunit'),
        ),
    ]
