# Generated by Django 4.0.2 on 2022-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitreport',
            options={'verbose_name_plural': 'Reports By Tenants'},
        ),
        migrations.AddField(
            model_name='unitreport',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unitreport',
            name='status',
            field=models.CharField(choices=[('rc', 'Received'), ('pr', 'Processing'), ('rs', 'Resolved'), ('dr', 'Dropped')], default='rr', max_length=5),
        ),
    ]
