# Generated by Django 4.0.2 on 2022-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_unitreport_options_unitreport_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitreport',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
