# Generated by Django 4.0.2 on 2022-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_unitreport_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='complaint_title',
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='name',
            field=models.CharField(default='anonymous', help_text='Leave blank for an anonymous complaint', max_length=60),
        ),
    ]
