# Generated by Django 4.0.2 on 2022-02-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0004_alter_building_building_status'),
        ('complaints', '0004_remove_complaints_complaint_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental_property.building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='body',
            field=models.TextField(max_length=155, verbose_name='Content'),
        ),
    ]
