# Generated by Django 4.0.2 on 2022-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaints_building_alter_complaints_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='name',
            field=models.CharField(default='anonymous', help_text='Ignore field for an anonymous complaint', max_length=60),
        ),
    ]
