# Generated by Django 4.0.2 on 2022-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaints_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, choices=[('rc', 'Received'), ('rs', 'Resolved')], max_length=5, null=True),
        ),
    ]
