# Generated by Django 4.0.2 on 2022-03-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_complaints_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('resolved', 'Resolved')], max_length=12, null=True),
        ),
    ]
