# Generated by Django 4.0.2 on 2022-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_alter_complaints_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('resolved', 'Resolved')], default='received', max_length=12),
        ),
    ]
