# Generated by Django 4.0.2 on 2022-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_alter_complaints_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_for', models.CharField(help_text='objective of this contact', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('forum', 'Forum')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Contact',
                'verbose_name_plural': 'Help Contact',
            },
        ),
    ]
