# Generated by Django 4.0.2 on 2022-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_helpcontacts_make_publicly_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitreport',
            name='other',
            field=models.CharField(blank=True, help_text='other type of isses...', max_length=100, null=True),
        ),
    ]
