# Generated by Django 4.0.2 on 2022-03-21 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_managers_active_phone_number_and_more'),
        ('rental_property', '0011_alter_rentalunit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('measuring_unit', models.CharField(default='KWH', max_length=20)),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('lock_cycle', models.BooleanField(default=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('due_date', models.DateField()),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Billing 3 | Electricity Billing Cycles',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='mpesa, bank transfer e.g. kcb', max_length=30)),
                ('account_name', models.CharField(max_length=50)),
                ('paybill_number', models.CharField(blank=True, help_text='Not required for bank transfer', max_length=20, null=True)),
                ('account_number', models.CharField(max_length=30)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Options',
            },
        ),
        migrations.CreateModel(
            name='WaterBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('units', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Unit Price (KES)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('month', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47, null=True)),
                ('meter_rent', models.DecimalField(decimal_places=2, default=50, max_digits=9)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('lock_cycle', models.BooleanField(default=False)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Billing 2 | Water Billing Cycles',
            },
        ),
        migrations.CreateModel(
            name='WaterPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_code', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(help_text='e.g. MPESA, KCB ...', max_length=30)),
                ('date_paid', models.DateField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True, max_length=155, null=True, verbose_name='Message?')),
                ('lock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.waterbilling')),
            ],
            options={
                'verbose_name': 'Billing 2 | Water Billing Payments',
                'verbose_name_plural': 'Billing 2 | Water Billing Payments',
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('ssid', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_meters', to='rental_property.rentalunit')),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('reading_added', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.waterbilling')),
            ],
        ),
        migrations.AddField(
            model_name='waterbilling',
            name='meter_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.watermeter'),
        ),
        migrations.AddField(
            model_name='waterbilling',
            name='rental_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.rentalunit'),
        ),
        migrations.AddField(
            model_name='waterbilling',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants'),
        ),
        migrations.CreateModel(
            name='UnitRentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pay_for_month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('cleared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('refunded', 'Refunded'), ('open', 'open'), ('closed', 'closed'), ('defaulted', 'Defaulted')], default='open', max_length=15)),
                ('rent_type', models.CharField(choices=[('rent', 'Monthly Rent'), ('s_deposit', 'Security Deposit')], default='rent', max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('notify_tenant', models.BooleanField(default=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.tenants')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.rentalunit')),
            ],
            options={
                'verbose_name': 'Rent For Unit',
                'verbose_name_plural': 'Billing 1 | Rent Details',
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_code', models.CharField(max_length=155)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paid_for_month', multiselectfield.db.fields.MultiSelectField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_with_stripe', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason, if rejected')),
                ('confirmed', models.BooleanField(default=False)),
                ('notify_tenant', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_manager', to='accounts.managers')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.paymentmethods')),
                ('rent_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='utilities.unitrentdetails')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='accounts.tenants')),
            ],
            options={
                'verbose_name_plural': 'Billing 1 | Rent Payments',
            },
        ),
        migrations.CreateModel(
            name='PayOnlineMpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=225)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reference', models.CharField(max_length=255)),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.unitrentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('units', models.DecimalField(decimal_places=2, max_digits=9)),
                ('reading_date', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.electricitybilling')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_code', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(help_text='e.g. MPESA, KCB ...', max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Message?')),
                ('lock', models.BooleanField(default=False)),
                ('payment_date', models.DateField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.electricitybilling')),
            ],
            options={
                'verbose_name': 'Billing 3 | Electricity Bill Payments',
                'verbose_name_plural': 'Billing 3 | Electricity Bill Payments',
            },
        ),
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('ssid', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_meters', to='rental_property.rentalunit')),
            ],
        ),
        migrations.AddField(
            model_name='electricitybilling',
            name='meter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.electricitymeter'),
        ),
        migrations.AddField(
            model_name='electricitybilling',
            name='rental_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.rentalunit'),
        ),
        migrations.AddField(
            model_name='electricitybilling',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants'),
        ),
    ]
