# Generated by Django 4.0.2 on 2022-03-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_payonlinempesa_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payonlinempesa',
            options={'verbose_name': 'Mpesa Online Payments', 'verbose_name_plural': 'Mpesa Online Payments'},
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='description',
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='timestamp',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='paid_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.unitrentdetails'),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='reference',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
