# Generated by Django 4.0.2 on 2022-03-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0015_alter_maintanancenotice_maintanance_status'),
        ('accounts', '0007_alter_managers_active_phone_number_and_more'),
        ('utilities', '0006_rentpayment_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentIncrementNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_all', models.BooleanField(default=False)),
                ('re', models.CharField(max_length=155, verbose_name='RE: ')),
                ('notice_detail', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.building')),
                ('to_tenants', models.ManyToManyField(to='accounts.Tenants')),
            ],
        ),
    ]
