# Generated by Django 4.0.2 on 2022-03-24 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_rentincrementnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentincrementnotice',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rentincrementnotice',
            name='takes_effect_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentincrementnotice',
            name='re',
            field=models.CharField(default='Rent Increase', max_length=155, verbose_name='RE: '),
        ),
        migrations.AlterField(
            model_name='unitrentdetails',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text='This field will be populated automatically', max_digits=9),
        ),
    ]
