# Generated by Django 4.0.2 on 2022-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_managers_active_phone_number_and_more'),
        ('utilities', '0008_rentincrementnotice_ref_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentincrementnotice',
            name='to_tenants',
            field=models.ManyToManyField(blank=True, to='accounts.Tenants'),
        ),
    ]
