# Generated by Django 4.0.2 on 2022-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_alter_rentincrementnotice_to_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentincrementnotice',
            name='notify_all',
            field=models.BooleanField(default=True),
        ),
    ]
