# Generated by Django 4.0.2 on 2022-03-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0016_rentalunit_rent_amount'),
        ('accounts', '0007_alter_managers_active_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0010_alter_rentincrementnotice_notify_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentincrementnotice',
            name='notify_all',
            field=models.BooleanField(default=True, verbose_name='Send TO All Tenants'),
        ),
        migrations.CreateModel(
            name='RentDefaulters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaulted_status', models.CharField(choices=[('active', 'Active'), ('cleared', 'Cleared')], default='active', max_length=20)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_property.building')),
                ('site_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenancy_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants')),
            ],
        ),
    ]
