# Generated by Django 4.0.2 on 2022-03-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0011_alter_rentincrementnotice_notify_all_rentdefaulters'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdefaulters',
            name='parent_defaults',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilities.unitrentdetails'),
            preserve_default=False,
        ),
    ]
