# Generated by Django 4.0.2 on 2022-03-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_rentdefaulters_parent_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdefaulters',
            name='parent_defaults',
        ),
        migrations.AddField(
            model_name='unitrentdetails',
            name='linked_to_defaulters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.rentdefaulters'),
        ),
    ]
