# Generated by Django 4.0.2 on 2022-03-24 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0014_alter_rentdefaulters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdefaulters',
            name='site_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated Account'),
        ),
    ]
