# Generated by Django 4.0.2 on 2022-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_alter_rentdefaulters_site_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payonlinempesa',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='organization_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
