# Generated by Django 4.0.2 on 2022-03-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0016_alter_payonlinempesa_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payonlinempesa',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='results_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='resultsdesc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payonlinempesa',
            name='reference',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
