# Generated by Django 4.0.2 on 2022-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0018_alter_payonlinempesa_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='organization_balance',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='paid_for',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='results_code',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='resultsdesc',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payonlinempesa',
            name='type',
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='MpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='ResultCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='ResultDesc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='TransactionDate',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
