# Generated by Django 4.0.2 on 2022-03-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0019_remove_payonlinempesa_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releif_detail', models.TextField()),
                ('expires', models.DateTimeField()),
                ('defaulter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.rentdefaulters')),
            ],
        ),
    ]
