# Generated by Django 4.0.2 on 2022-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0020_temporaryrelief'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryrelief',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='expired', max_length=10),
        ),
    ]
