# Generated by Django 4.0.2 on 2022-03-25 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0021_temporaryrelief_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryrelief',
            old_name='releif_detail',
            new_name='relief_detail',
        ),
        migrations.AddField(
            model_name='temporaryrelief',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryrelief',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
