# Generated by Django 4.0.2 on 2022-03-25 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0022_rename_releif_detail_temporaryrelief_relief_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryrelief',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='temporaryrelief',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10),
        ),
    ]
