# Generated by Django 4.0.2 on 2022-03-25 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0023_alter_temporaryrelief_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryrelief',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
