# Generated by Django 4.0.2 on 2022-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0024_alter_temporaryrelief_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryrelief',
            name='already_sent',
            field=models.BooleanField(default=False),
        ),
    ]
