# Generated by Django 4.0.2 on 2022-03-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_managers_active_phone_number_and_more'),
        ('utilities', '0025_temporaryrelief_already_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payonlinempesa',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.unitrentdetails'),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenants'),
        ),
        migrations.AddField(
            model_name='payonlinempesa',
            name='update_status',
            field=models.CharField(default='recieved', max_length=10),
        ),
    ]
