# Generated by Django 4.0.3 on 2022-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybilling',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=24.18, max_digits=9),
        ),
        migrations.AlterField(
            model_name='mpesaonline',
            name='update_status',
            field=models.CharField(choices=[('recieved', 'Recieved'), ('updated', 'Updated')], default='recieved', max_length=10),
        ),
        migrations.AlterField(
            model_name='waterbilling',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=53.0, max_digits=9, verbose_name='Unit Price (KES)'),
        ),
    ]
